#!/usr/bin/env python
# -*- coding: utf-8 -*-
from stemming import Stemming

stemmer=Stemming();

print(stemmer.stem("aufeinander"))
print(stemmer.stem("aufeinanderbiss"))
print(stemmer.stem("aufeinanderfolge"))
print(stemmer.stem("aufeinanderfolgen"))
print(stemmer.stem("aufeinanderfolgend"))
print(stemmer.stem("aufeinanderfolgende"))
print(stemmer.stem("aufeinanderfolgenden"))
print(stemmer.stem("aufeinanderfolgender"))
print(stemmer.stem("aufeinanderfolgt"))
print(stemmer.stem("aufeinanderfolgten"))
print(stemmer.stem("aufeinanderschlügen"))
print(stemmer.stem("aufenthalt"))
print(stemmer.stem("aufenthalten"))
print(stemmer.stem("aufenthaltes"))
print(stemmer.stem("auferlegen"))
print(stemmer.stem("auferlegt"))
print(stemmer.stem("auferlegten"))
print(stemmer.stem("auferstand"))
print(stemmer.stem("auferstanden"))
print(stemmer.stem("auferstehen"))
print(stemmer.stem("aufersteht"))
print(stemmer.stem("auferstehung"))
print(stemmer.stem("auferstünde"))
print(stemmer.stem("auferwecken"))
print(stemmer.stem("auferweckt"))
print(stemmer.stem("auferzogen"))
print(stemmer.stem("aufessen"))
print(stemmer.stem("auffa"))
print(stemmer.stem("auffallen"))
print(stemmer.stem("auffallend"))
print(stemmer.stem("auffallenden"))
print(stemmer.stem("auffallender"))
print(stemmer.stem("auffällig"))
print(stemmer.stem("auffälligen"))
print(stemmer.stem("auffälliges"))
print(stemmer.stem("auffassen"))
print(stemmer.stem("auffasst"))
print(stemmer.stem("auffaßt"))
print(stemmer.stem("auffassung"))
print(stemmer.stem("auffassungsvermögen"))